#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#! Startup scripts
# I should just put all of this in some init script
setxkbmap us
xsetroot -solid "#556270" 
feh --bg-scale ~/media/pictures/wallpaper/moonrise_desktop.jpg
sxhkd &
